# Generated by Django 2.1.4 on 2018-12-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('stu_id', models.IntegerField()),
                ('cyc_id', models.IntegerField()),
            ],
        ),
    ]
