# Generated by Django 2.1.4 on 2018-12-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cyc_id',
            new_name='cycle_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='stu_id',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='username',
        ),
    ]
